-- Require all the plugins in one place
require("user.plugin-configurations.nvim-tree")
require("user.plugin-configurations.lualine")
require("user.plugin-configurations.treesitter")
require("user.plugin-configurations.colorscheme")
require("user.plugin-configurations.telescope")
require("user.plugin-configurations.nvim-autopairs")
require("user.plugin-configurations.surround")
require("user.plugin-configurations.copilot")
require("user.plugin-configurations.null-ls")
require("user.plugin-configurations.cmp")
require("user.plugin-configurations.mason")
require("user.plugin-configurations.neodev")
require("user.plugin-configurations.lspconfig")
require("user.plugin-configurations.which-key")
require("user.plugin-configurations.todo-comments")
require("user.plugin-configurations.harpoon")
require("user.plugin-configurations.simple-note")
