#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find \
      ~/Sites/prive \
      ~/Sites/marketingcloud \
      ~/Sites/salesforce \
      ~/Sites/novti  \
      ~/Sites/novti/admin  \
      ~/Sites/novti/bundles  \
        -mindepth 1 \
        -maxdepth 2 \
        -type d | \
        fzf-tmux \
      )
fi

if [[ -z $selected ]]; then
    print 'Nothing select...'
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# you are not in tmux
if [[ -z $TMUX ]]; then
    if ! tmux has-session -t "$selected_name" 2>/dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi
    tmux attach -t "$selected_name"
# you are in tmux
elif [[ -n $TMUX ]]; then
    if ! tmux has-session -t "$selected_name" 2>/dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi
    tmux switch-client -t "$selected_name"
fi
